# Generated by Django 5.2.5 on 2025-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20220716_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
